# Site settings
title: FDCL
tag_text: Flight Dynamics and Control Lab
description: Flight Dynamics and Control Laboratory at the George Washington University
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Github API
repository: fdcl-gwu/fdcl-gwu.github.io

plugins:
  - "jekyll-github-metadata"
